title: The Heraclitus Project
description: Documentation of the Heraclitus Project products
theme: just-the-docs

url: https://docs.heraclitus.space

aux_links:
  Website: https://heraclitus.space
  Telegram: https://t.me/heraclitus_project_channel
  Twitter: https://twitter.com/heraclitus_tci
  Medium: https://medium.com/@heraclitus_project
  Github: https://github.com/heraclitusproject/documentation
