title: The Heraclitus Project
description: Documentation of the Heraclitus Project products
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/heraclitusproject/documentation
